#!/usr/bin/env sh

shopt -s nullglob
for f in pages/*.md; do
  MD="${f##*/}"
  HTML="${MD%.md}".html
  cat src/header.html > built/$HTML
  node_modules/remark-cli/cli.js -u remark-html $f >> built/$HTML
  cat src/footer.html >> built/$HTML
done

NEW_HASH="$(ipfs add built -r | cut -d' ' -f2 | tail -n1)"
echo "Publishing the new hash: $NEW_HASH"
ipfs name publish $NEW_HASH

PEER_ID="$(ipfs id | node_modules/jq2/index.js '$.ID')"
node_modules/opn-cli/cli.js "http://gateway.ipfs.io/ipns/$PEER_ID"

