#!/usr/bin/env sh

shopt -s nullglob
for f in pages/*.md; do
  file="${f##*/}"
  html="${file%.md}".html
  cat src/header.html > built/$html
  node_modules/remark-cli/cli.js -u remark-html pages/$root.md >> built/$html
  cat src/footer.html >> built/$html
done

NEW_HASH="$(ipfs add built -r | cut -d' ' -f2 | tail -n1)"
echo "Publishing the new hash"
ipfs name publish $NEW_HASH

PEER_ID="$(ipfs id | node_modules/jq2/index.js '$.ID')"
URL="http://gateway.ipfs.io/ipns/$PEER_ID"
node_modules/opn-cli/cli.js $URL

